logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG

spring:
  application:
   name: spring-web-jdk17

  datasource:
    url: ${AZURE_DB_CONNECTION_STRING}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  cloud:
    azure:
      storage:
        blob:
          container-name: images
          connection-string: ${AZURE_BLOB_CONNECTION_STRING}

#  sql:
#    init:
#      mode: always

  config:
    import: "optional:file:secrets.yml"
#    import: "classpath:secrets.yml"
#    import: "optional:classpath:optional-config.yml"
