name: Env Test 1

on:
  workflow_dispatch:

env:
  AZURE_DB: ${{ secrets.AZURE_DB }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: |
          echo "1.1 sec is ${{ secrets.AZURE_DB }}"
          echo "1.2 env is ${{ env.AZURE_DB }}"
          echo "1.3 vars is ${{ vars.AZURE_DB }}"

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: "Development"

    steps:
      - name: print2
        run: |
          echo "2.1 sec is ${{ secrets.AZURE_DB }}"
          echo "2.2 env is ${{ env.AZURE_DB }}"
          echo "2.3 vars is ${{ vars.AZURE_DB }}"
